#!/usr/bin/env python3
"""backlog_release_metrics v1.1.0 — every release number, generated not written.

Exists because a hand-written number reached a changelog and did not reproduce.
The v1.14.0 entry claimed "32 undocumented classes"; the shipped gate reports
29 (62 of 91 named) on the same inputs. The 32 was arrived at by adding a manual
probe of 17 terms — classes AND properties — to a later gate run of 15 classes:
two different populations, summed. No tool ever produced it.

B3 is explicit that an externally-verifiable claim must be re-executed rather
than asserted. A release note full of figures is a dense collection of exactly
such claims, so the figures must come from a generated file that a reader can
regenerate, not from arithmetic performed while writing prose.

Run this AFTER build_manifest, never before. The metrics record the result of
running the gates, and one of those gates verifies the manifest; generating them
first produces a file whose Gate 0 reports mismatches against a manifest that had
not been rebuilt yet. RELEASE_METRICS.txt is excluded from the manifest, and NOT for the reason the
first version of this note gave. A manifest cannot contain its own hash — that is
containment, a physical impossibility. This file *could* be hashed; it is excluded
because it **reports the result of the manifest gate**, so covering it creates a
generation-order cycle: hash the metrics, and the metrics describe a manifest that
no longer matches. The consequence is different and worse, which is why it must be
stated accurately: the manifest's integrity is self-evident the moment anyone
verifies it, while this file's integrity is not covered at all. Its only guarantee
is that it regenerates byte-for-byte — so it must contain nothing derived from the
environment it ran in.

Quote it verbatim in the changelog; do not retype or combine.

Usage: backlog_release_metrics_v1_1_0.py [--pack /path/to/oepack]
"""
import argparse, glob, hashlib, os, subprocess, sys

PKG = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
HERE = os.path.join(PKG, "03-tooling")


def latest(pattern):
    hits = sorted(glob.glob(os.path.join(HERE, pattern)))
    return hits[-1] if hits else None


def run(cmd):
    p = subprocess.run(cmd, capture_output=True, text=True, cwd=PKG)
    return (p.stdout or "") + (p.stderr or "")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--pack", default=None)
    args = ap.parse_args()

    version = open(os.path.join(PKG, "VERSION.txt")).read().strip()
    # No wall-clock stamp: a generation time is environment, not evidence, and it
    # alone would defeat the byte-reproducibility this file's integrity rests on.
    # The manifest digest ties these figures to an exact package state and is
    # itself derived from files, so it reproduces.
    man = os.path.join(PKG, "MANIFEST_SHA256.txt")
    man_digest = hashlib.sha256(open(man, "rb").read()).hexdigest() if os.path.exists(man) else "no manifest"
    blocks = [("release", "backlog-roadmap-framework v" + version
               + "\nmanifest SHA-256 " + man_digest
               + "\ngenerated by backlog_release_metrics_v1_1_0.py - reproducible from files alone")]

    gate = latest("backlog_gate_v*.sh")
    if gate:
        blocks.append(("release gate (all steps)", run(["bash", gate])))
    doc = latest("backlog_doc_coverage_gate_v*.py")
    if doc:
        blocks.append(("doc-coverage gate", run([sys.executable, doc])))
    qa = latest("backlog_quality_assessment_v*.py")
    if qa:
        blocks.append(("quality metrics", run([sys.executable, qa])))
    if args.pack:
        rd = latest("backlog_registration_readiness_v*.py")
        if rd:
            blocks.append(("ORCP readiness (--pack given)", run([sys.executable, rd, "--pack", args.pack])))
        pc = latest("backlog_package_check_v*.py")
        fixtures = sorted(glob.glob(os.path.join(HERE, "fixtures", "fixture_positive_v*.ttl")))
        if pc and fixtures:
            blocks.append(("package check (--pack given)", run([sys.executable, pc, fixtures[-1], "--pack", args.pack])))
    else:
        blocks.append(("ORCP readiness / package check", "NOT RUN — no --pack given. Not assumed to pass."))

    out = []
    for title, body in blocks:
        out.append("=" * 78)
        out.append("== %s" % title)
        out.append("=" * 78)
        out.append(body.rstrip())
        out.append("")
    text = "\n".join(out) + "\n"
    path = os.path.join(PKG, "RELEASE_METRICS.txt")
    open(path, "w").write(text)
    print(text)
    print("written: RELEASE_METRICS.txt (%d bytes) — run build_manifest AFTER this" % len(text))
    return 0


if __name__ == "__main__":
    sys.exit(main())
